package greendao.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "HISTORY".
 */
public class History {

    /** Not-null value. */
    private String searchContent;
    private String searchType;
    private java.util.Date searchDate;

    public History() {
    }

    public History(String searchContent) {
        this.searchContent = searchContent;
    }

    public History(String searchContent, String searchType, java.util.Date searchDate) {
        this.searchContent = searchContent;
        this.searchType = searchType;
        this.searchDate = searchDate;
    }

    /** Not-null value. */
    public String getSearchContent() {
        return searchContent;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setSearchContent(String searchContent) {
        this.searchContent = searchContent;
    }

    public String getSearchType() {
        return searchType;
    }

    public void setSearchType(String searchType) {
        this.searchType = searchType;
    }

    public java.util.Date getSearchDate() {
        return searchDate;
    }

    public void setSearchDate(java.util.Date searchDate) {
        this.searchDate = searchDate;
    }

}
