package greendao.dao;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.database.Database;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;
import greendao.bean.Activity;
import greendao.bean.Airline;
import greendao.bean.App;
import greendao.bean.Article;
import greendao.bean.Attraction;
import greendao.bean.Collection;
import greendao.bean.Comment;
import greendao.bean.Contact;
import greendao.bean.Document;
import greendao.bean.DraftBox;
import greendao.bean.Food;
import greendao.bean.Guide;
import greendao.bean.GuideGroup;
import greendao.bean.History;
import greendao.bean.Hotel;
import greendao.bean.Location;
import greendao.bean.Mall;
import greendao.bean.Menu;
import greendao.bean.MenuItem;
import greendao.bean.MenuItemOption;
import greendao.bean.MenuSection;
import greendao.bean.Place;
import greendao.bean.Product;
import greendao.bean.Restaurant;
import greendao.bean.Route;
import greendao.bean.Station;
import greendao.bean.Visa;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig locationDaoConfig;
    private final DaoConfig guideGroupDaoConfig;
    private final DaoConfig guideDaoConfig;
    private final DaoConfig visaDaoConfig;
    private final DaoConfig articleDaoConfig;
    private final DaoConfig foodDaoConfig;
    private final DaoConfig contactDaoConfig;
    private final DaoConfig appDaoConfig;
    private final DaoConfig productDaoConfig;
    private final DaoConfig routeDaoConfig;
    private final DaoConfig placeDaoConfig;
    private final DaoConfig hotelDaoConfig;
    private final DaoConfig restaurantDaoConfig;
    private final DaoConfig attractionDaoConfig;
    private final DaoConfig menuDaoConfig;
    private final DaoConfig menuSectionDaoConfig;
    private final DaoConfig menuItemDaoConfig;
    private final DaoConfig menuItemOptionDaoConfig;
    private final DaoConfig commentDaoConfig;
    private final DaoConfig documentDaoConfig;
    private final DaoConfig airlineDaoConfig;
    private final DaoConfig activityDaoConfig;
    private final DaoConfig mallDaoConfig;
    private final DaoConfig stationDaoConfig;
    private final DaoConfig collectionDaoConfig;
    private final DaoConfig draftBoxDaoConfig;
    private final DaoConfig historyDaoConfig;

    private final LocationDao locationDao;
    private final GuideGroupDao guideGroupDao;
    private final GuideDao guideDao;
    private final VisaDao visaDao;
    private final ArticleDao articleDao;
    private final FoodDao foodDao;
    private final ContactDao contactDao;
    private final AppDao appDao;
    private final ProductDao productDao;
    private final RouteDao routeDao;
    private final PlaceDao placeDao;
    private final HotelDao hotelDao;
    private final RestaurantDao restaurantDao;
    private final AttractionDao attractionDao;
    private final MenuDao menuDao;
    private final MenuSectionDao menuSectionDao;
    private final MenuItemDao menuItemDao;
    private final MenuItemOptionDao menuItemOptionDao;
    private final CommentDao commentDao;
    private final DocumentDao documentDao;
    private final AirlineDao airlineDao;
    private final ActivityDao activityDao;
    private final MallDao mallDao;
    private final StationDao stationDao;
    private final CollectionDao collectionDao;
    private final DraftBoxDao draftBoxDao;
    private final HistoryDao historyDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        locationDaoConfig = daoConfigMap.get(LocationDao.class).clone();
        locationDaoConfig.initIdentityScope(type);

        guideGroupDaoConfig = daoConfigMap.get(GuideGroupDao.class).clone();
        guideGroupDaoConfig.initIdentityScope(type);

        guideDaoConfig = daoConfigMap.get(GuideDao.class).clone();
        guideDaoConfig.initIdentityScope(type);

        visaDaoConfig = daoConfigMap.get(VisaDao.class).clone();
        visaDaoConfig.initIdentityScope(type);

        articleDaoConfig = daoConfigMap.get(ArticleDao.class).clone();
        articleDaoConfig.initIdentityScope(type);

        foodDaoConfig = daoConfigMap.get(FoodDao.class).clone();
        foodDaoConfig.initIdentityScope(type);

        contactDaoConfig = daoConfigMap.get(ContactDao.class).clone();
        contactDaoConfig.initIdentityScope(type);

        appDaoConfig = daoConfigMap.get(AppDao.class).clone();
        appDaoConfig.initIdentityScope(type);

        productDaoConfig = daoConfigMap.get(ProductDao.class).clone();
        productDaoConfig.initIdentityScope(type);

        routeDaoConfig = daoConfigMap.get(RouteDao.class).clone();
        routeDaoConfig.initIdentityScope(type);

        placeDaoConfig = daoConfigMap.get(PlaceDao.class).clone();
        placeDaoConfig.initIdentityScope(type);

        hotelDaoConfig = daoConfigMap.get(HotelDao.class).clone();
        hotelDaoConfig.initIdentityScope(type);

        restaurantDaoConfig = daoConfigMap.get(RestaurantDao.class).clone();
        restaurantDaoConfig.initIdentityScope(type);

        attractionDaoConfig = daoConfigMap.get(AttractionDao.class).clone();
        attractionDaoConfig.initIdentityScope(type);

        menuDaoConfig = daoConfigMap.get(MenuDao.class).clone();
        menuDaoConfig.initIdentityScope(type);

        menuSectionDaoConfig = daoConfigMap.get(MenuSectionDao.class).clone();
        menuSectionDaoConfig.initIdentityScope(type);

        menuItemDaoConfig = daoConfigMap.get(MenuItemDao.class).clone();
        menuItemDaoConfig.initIdentityScope(type);

        menuItemOptionDaoConfig = daoConfigMap.get(MenuItemOptionDao.class).clone();
        menuItemOptionDaoConfig.initIdentityScope(type);

        commentDaoConfig = daoConfigMap.get(CommentDao.class).clone();
        commentDaoConfig.initIdentityScope(type);

        documentDaoConfig = daoConfigMap.get(DocumentDao.class).clone();
        documentDaoConfig.initIdentityScope(type);

        airlineDaoConfig = daoConfigMap.get(AirlineDao.class).clone();
        airlineDaoConfig.initIdentityScope(type);

        activityDaoConfig = daoConfigMap.get(ActivityDao.class).clone();
        activityDaoConfig.initIdentityScope(type);

        mallDaoConfig = daoConfigMap.get(MallDao.class).clone();
        mallDaoConfig.initIdentityScope(type);

        stationDaoConfig = daoConfigMap.get(StationDao.class).clone();
        stationDaoConfig.initIdentityScope(type);

        collectionDaoConfig = daoConfigMap.get(CollectionDao.class).clone();
        collectionDaoConfig.initIdentityScope(type);

        draftBoxDaoConfig = daoConfigMap.get(DraftBoxDao.class).clone();
        draftBoxDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        locationDao = new LocationDao(locationDaoConfig, this);
        guideGroupDao = new GuideGroupDao(guideGroupDaoConfig, this);
        guideDao = new GuideDao(guideDaoConfig, this);
        visaDao = new VisaDao(visaDaoConfig, this);
        articleDao = new ArticleDao(articleDaoConfig, this);
        foodDao = new FoodDao(foodDaoConfig, this);
        contactDao = new ContactDao(contactDaoConfig, this);
        appDao = new AppDao(appDaoConfig, this);
        productDao = new ProductDao(productDaoConfig, this);
        routeDao = new RouteDao(routeDaoConfig, this);
        placeDao = new PlaceDao(placeDaoConfig, this);
        hotelDao = new HotelDao(hotelDaoConfig, this);
        restaurantDao = new RestaurantDao(restaurantDaoConfig, this);
        attractionDao = new AttractionDao(attractionDaoConfig, this);
        menuDao = new MenuDao(menuDaoConfig, this);
        menuSectionDao = new MenuSectionDao(menuSectionDaoConfig, this);
        menuItemDao = new MenuItemDao(menuItemDaoConfig, this);
        menuItemOptionDao = new MenuItemOptionDao(menuItemOptionDaoConfig, this);
        commentDao = new CommentDao(commentDaoConfig, this);
        documentDao = new DocumentDao(documentDaoConfig, this);
        airlineDao = new AirlineDao(airlineDaoConfig, this);
        activityDao = new ActivityDao(activityDaoConfig, this);
        mallDao = new MallDao(mallDaoConfig, this);
        stationDao = new StationDao(stationDaoConfig, this);
        collectionDao = new CollectionDao(collectionDaoConfig, this);
        draftBoxDao = new DraftBoxDao(draftBoxDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);

        registerDao(Location.class, locationDao);
        registerDao(GuideGroup.class, guideGroupDao);
        registerDao(Guide.class, guideDao);
        registerDao(Visa.class, visaDao);
        registerDao(Article.class, articleDao);
        registerDao(Food.class, foodDao);
        registerDao(Contact.class, contactDao);
        registerDao(App.class, appDao);
        registerDao(Product.class, productDao);
        registerDao(Route.class, routeDao);
        registerDao(Place.class, placeDao);
        registerDao(Hotel.class, hotelDao);
        registerDao(Restaurant.class, restaurantDao);
        registerDao(Attraction.class, attractionDao);
        registerDao(Menu.class, menuDao);
        registerDao(MenuSection.class, menuSectionDao);
        registerDao(MenuItem.class, menuItemDao);
        registerDao(MenuItemOption.class, menuItemOptionDao);
        registerDao(Comment.class, commentDao);
        registerDao(Document.class, documentDao);
        registerDao(Airline.class, airlineDao);
        registerDao(Activity.class, activityDao);
        registerDao(Mall.class, mallDao);
        registerDao(Station.class, stationDao);
        registerDao(Collection.class, collectionDao);
        registerDao(DraftBox.class, draftBoxDao);
        registerDao(History.class, historyDao);
    }
    
    public void clear() {
        locationDaoConfig.getIdentityScope().clear();
        guideGroupDaoConfig.getIdentityScope().clear();
        guideDaoConfig.getIdentityScope().clear();
        visaDaoConfig.getIdentityScope().clear();
        articleDaoConfig.getIdentityScope().clear();
        foodDaoConfig.getIdentityScope().clear();
        contactDaoConfig.getIdentityScope().clear();
        appDaoConfig.getIdentityScope().clear();
        productDaoConfig.getIdentityScope().clear();
        routeDaoConfig.getIdentityScope().clear();
        placeDaoConfig.getIdentityScope().clear();
        hotelDaoConfig.getIdentityScope().clear();
        restaurantDaoConfig.getIdentityScope().clear();
        attractionDaoConfig.getIdentityScope().clear();
        menuDaoConfig.getIdentityScope().clear();
        menuSectionDaoConfig.getIdentityScope().clear();
        menuItemDaoConfig.getIdentityScope().clear();
        menuItemOptionDaoConfig.getIdentityScope().clear();
        commentDaoConfig.getIdentityScope().clear();
        documentDaoConfig.getIdentityScope().clear();
        airlineDaoConfig.getIdentityScope().clear();
        activityDaoConfig.getIdentityScope().clear();
        mallDaoConfig.getIdentityScope().clear();
        stationDaoConfig.getIdentityScope().clear();
        collectionDaoConfig.getIdentityScope().clear();
        draftBoxDaoConfig.getIdentityScope().clear();
        historyDaoConfig.getIdentityScope().clear();
    }

    public LocationDao getLocationDao() {
        return locationDao;
    }

    public GuideGroupDao getGuideGroupDao() {
        return guideGroupDao;
    }

    public GuideDao getGuideDao() {
        return guideDao;
    }

    public VisaDao getVisaDao() {
        return visaDao;
    }

    public ArticleDao getArticleDao() {
        return articleDao;
    }

    public FoodDao getFoodDao() {
        return foodDao;
    }

    public ContactDao getContactDao() {
        return contactDao;
    }

    public AppDao getAppDao() {
        return appDao;
    }

    public ProductDao getProductDao() {
        return productDao;
    }

    public RouteDao getRouteDao() {
        return routeDao;
    }

    public PlaceDao getPlaceDao() {
        return placeDao;
    }

    public HotelDao getHotelDao() {
        return hotelDao;
    }

    public RestaurantDao getRestaurantDao() {
        return restaurantDao;
    }

    public AttractionDao getAttractionDao() {
        return attractionDao;
    }

    public MenuDao getMenuDao() {
        return menuDao;
    }

    public MenuSectionDao getMenuSectionDao() {
        return menuSectionDao;
    }

    public MenuItemDao getMenuItemDao() {
        return menuItemDao;
    }

    public MenuItemOptionDao getMenuItemOptionDao() {
        return menuItemOptionDao;
    }

    public CommentDao getCommentDao() {
        return commentDao;
    }

    public DocumentDao getDocumentDao() {
        return documentDao;
    }

    public AirlineDao getAirlineDao() {
        return airlineDao;
    }

    public ActivityDao getActivityDao() {
        return activityDao;
    }

    public MallDao getMallDao() {
        return mallDao;
    }

    public StationDao getStationDao() {
        return stationDao;
    }

    public CollectionDao getCollectionDao() {
        return collectionDao;
    }

    public DraftBoxDao getDraftBoxDao() {
        return draftBoxDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

}
