package greendao.dao;

import android.database.Cursor;

import java.util.ArrayList;
import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.database.Database;
import de.greenrobot.dao.database.DatabaseStatement;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;
import greendao.bean.Menu;
import greendao.bean.MenuSection;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "MENU_SECTION".
*/
public class MenuSectionDao extends AbstractDao<MenuSection, String> {

    public static final String TABLENAME = "MENU_SECTION";

    /**
     * Properties of entity MenuSection.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property ObjectId = new Property(0, String.class, "objectId", true, "OBJECT_ID");
        public final static Property Desc = new Property(1, String.class, "desc", false, "DESC");
        public final static Property Index = new Property(2, Integer.class, "index", false, "INDEX");
        public final static Property DescCn = new Property(3, String.class, "descCn", false, "DESC_CN");
        public final static Property Title = new Property(4, String.class, "title", false, "TITLE");
        public final static Property TitleCn = new Property(5, String.class, "titleCn", false, "TITLE_CN");
        public final static Property RowStatus = new Property(6, String.class, "rowStatus", false, "ROW_STATUS");
        public final static Property Items = new Property(7, String.class, "items", false, "ITEMS");
        public final static Property CreatedAt = new Property(8, String.class, "createdAt", false, "CREATED_AT");
        public final static Property UpdatedAt = new Property(9, String.class, "updatedAt", false, "UPDATED_AT");
        public final static Property MenuId = new Property(10, String.class, "menuId", false, "MENU_ID");
    };

    private DaoSession daoSession;

    private Query<MenuSection> menu_MenuSectionListQuery;

    public MenuSectionDao(DaoConfig config) {
        super(config);
    }
    
    public MenuSectionDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MENU_SECTION\" (" + //
                "\"OBJECT_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: objectId
                "\"DESC\" TEXT," + // 1: desc
                "\"INDEX\" INTEGER," + // 2: index
                "\"DESC_CN\" TEXT," + // 3: descCn
                "\"TITLE\" TEXT," + // 4: title
                "\"TITLE_CN\" TEXT," + // 5: titleCn
                "\"ROW_STATUS\" TEXT," + // 6: rowStatus
                "\"ITEMS\" TEXT," + // 7: items
                "\"CREATED_AT\" TEXT," + // 8: createdAt
                "\"UPDATED_AT\" TEXT," + // 9: updatedAt
                "\"MENU_ID\" TEXT);"); // 10: menuId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MENU_SECTION\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(DatabaseStatement stmt, MenuSection entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getObjectId());
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(2, desc);
        }
 
        Integer index = entity.getIndex();
        if (index != null) {
            stmt.bindLong(3, index);
        }
 
        String descCn = entity.getDescCn();
        if (descCn != null) {
            stmt.bindString(4, descCn);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(5, title);
        }
 
        String titleCn = entity.getTitleCn();
        if (titleCn != null) {
            stmt.bindString(6, titleCn);
        }
 
        String rowStatus = entity.getRowStatus();
        if (rowStatus != null) {
            stmt.bindString(7, rowStatus);
        }
 
        String items = entity.getItems();
        if (items != null) {
            stmt.bindString(8, items);
        }
 
        String createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindString(9, createdAt);
        }
 
        String updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindString(10, updatedAt);
        }
 
        String menuId = entity.getMenuId();
        if (menuId != null) {
            stmt.bindString(11, menuId);
        }
    }

    @Override
    protected void attachEntity(MenuSection entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public MenuSection readEntity(Cursor cursor, int offset) {
        MenuSection entity = new MenuSection( //
            cursor.getString(offset + 0), // objectId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // desc
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // index
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // descCn
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // title
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // titleCn
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // rowStatus
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // items
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // createdAt
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // updatedAt
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // menuId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, MenuSection entity, int offset) {
        entity.setObjectId(cursor.getString(offset + 0));
        entity.setDesc(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setIndex(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setDescCn(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTitle(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTitleCn(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setRowStatus(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setItems(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setCreatedAt(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setUpdatedAt(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setMenuId(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(MenuSection entity, long rowId) {
        return entity.getObjectId();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(MenuSection entity) {
        if(entity != null) {
            return entity.getObjectId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "menuSectionList" to-many relationship of Menu. */
    public List<MenuSection> _queryMenu_MenuSectionList(String menuId) {
        synchronized (this) {
            if (menu_MenuSectionListQuery == null) {
                QueryBuilder<MenuSection> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.MenuId.eq(null));
                menu_MenuSectionListQuery = queryBuilder.build();
            }
        }
        Query<MenuSection> query = menu_MenuSectionListQuery.forCurrentThread();
        query.setParameter(0, menuId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getMenuDao().getAllColumns());
            builder.append(" FROM MENU_SECTION T");
            builder.append(" LEFT JOIN MENU T0 ON T.\"MENU_ID\"=T0.\"OBJECT_ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected MenuSection loadCurrentDeep(Cursor cursor, boolean lock) {
        MenuSection entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Menu menu = loadCurrentOther(daoSession.getMenuDao(), cursor, offset);
        entity.setMenu(menu);

        return entity;    
    }

    public MenuSection loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<MenuSection> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<MenuSection> list = new ArrayList<MenuSection>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<MenuSection> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<MenuSection> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
