package greendao.dao;

import android.database.Cursor;

import java.util.ArrayList;
import java.util.List;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.database.Database;
import de.greenrobot.dao.database.DatabaseStatement;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.internal.SqlUtils;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;
import greendao.bean.Guide;
import greendao.bean.Visa;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table "VISA".
*/
public class VisaDao extends AbstractDao<Visa, String> {

    public static final String TABLENAME = "VISA";

    /**
     * Properties of entity Visa.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property ObjectId = new Property(0, String.class, "objectId", true, "OBJECT_ID");
        public final static Property VisaCode = new Property(1, String.class, "visaCode", false, "VISA_CODE");
        public final static Property Desc = new Property(2, String.class, "desc", false, "DESC");
        public final static Property Index = new Property(3, Integer.class, "index", false, "INDEX");
        public final static Property Title = new Property(4, String.class, "title", false, "TITLE");
        public final static Property RowStatus = new Property(5, String.class, "rowStatus", false, "ROW_STATUS");
        public final static Property Country = new Property(6, String.class, "country", false, "COUNTRY");
        public final static Property Articles = new Property(7, String.class, "articles", false, "ARTICLES");
        public final static Property CreatedAt = new Property(8, String.class, "createdAt", false, "CREATED_AT");
        public final static Property UpdatedAt = new Property(9, String.class, "updatedAt", false, "UPDATED_AT");
        public final static Property GuideId = new Property(10, String.class, "guideId", false, "GUIDE_ID");
    };

    private DaoSession daoSession;

    private Query<Visa> guide_VisaListQuery;

    public VisaDao(DaoConfig config) {
        super(config);
    }
    
    public VisaDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"VISA\" (" + //
                "\"OBJECT_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: objectId
                "\"VISA_CODE\" TEXT," + // 1: visaCode
                "\"DESC\" TEXT," + // 2: desc
                "\"INDEX\" INTEGER," + // 3: index
                "\"TITLE\" TEXT," + // 4: title
                "\"ROW_STATUS\" TEXT," + // 5: rowStatus
                "\"COUNTRY\" TEXT," + // 6: country
                "\"ARTICLES\" TEXT," + // 7: articles
                "\"CREATED_AT\" TEXT," + // 8: createdAt
                "\"UPDATED_AT\" TEXT," + // 9: updatedAt
                "\"GUIDE_ID\" TEXT);"); // 10: guideId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"VISA\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(DatabaseStatement stmt, Visa entity) {
        stmt.clearBindings();
        stmt.bindString(1, entity.getObjectId());
 
        String visaCode = entity.getVisaCode();
        if (visaCode != null) {
            stmt.bindString(2, visaCode);
        }
 
        String desc = entity.getDesc();
        if (desc != null) {
            stmt.bindString(3, desc);
        }
 
        Integer index = entity.getIndex();
        if (index != null) {
            stmt.bindLong(4, index);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(5, title);
        }
 
        String rowStatus = entity.getRowStatus();
        if (rowStatus != null) {
            stmt.bindString(6, rowStatus);
        }
 
        String country = entity.getCountry();
        if (country != null) {
            stmt.bindString(7, country);
        }
 
        String articles = entity.getArticles();
        if (articles != null) {
            stmt.bindString(8, articles);
        }
 
        String createdAt = entity.getCreatedAt();
        if (createdAt != null) {
            stmt.bindString(9, createdAt);
        }
 
        String updatedAt = entity.getUpdatedAt();
        if (updatedAt != null) {
            stmt.bindString(10, updatedAt);
        }
 
        String guideId = entity.getGuideId();
        if (guideId != null) {
            stmt.bindString(11, guideId);
        }
    }

    @Override
    protected void attachEntity(Visa entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    /** @inheritdoc */
    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.getString(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Visa readEntity(Cursor cursor, int offset) {
        Visa entity = new Visa( //
            cursor.getString(offset + 0), // objectId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // visaCode
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // desc
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // index
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // title
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // rowStatus
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // country
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // articles
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // createdAt
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // updatedAt
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10) // guideId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Visa entity, int offset) {
        entity.setObjectId(cursor.getString(offset + 0));
        entity.setVisaCode(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setDesc(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIndex(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setTitle(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setRowStatus(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCountry(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setArticles(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setCreatedAt(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setUpdatedAt(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setGuideId(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
     }
    
    /** @inheritdoc */
    @Override
    protected String updateKeyAfterInsert(Visa entity, long rowId) {
        return entity.getObjectId();
    }
    
    /** @inheritdoc */
    @Override
    public String getKey(Visa entity) {
        if(entity != null) {
            return entity.getObjectId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "visaList" to-many relationship of Guide. */
    public List<Visa> _queryGuide_VisaList(String guideId) {
        synchronized (this) {
            if (guide_VisaListQuery == null) {
                QueryBuilder<Visa> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.GuideId.eq(null));
                guide_VisaListQuery = queryBuilder.build();
            }
        }
        Query<Visa> query = guide_VisaListQuery.forCurrentThread();
        query.setParameter(0, guideId);
        return query.list();
    }

    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getGuideDao().getAllColumns());
            builder.append(" FROM VISA T");
            builder.append(" LEFT JOIN GUIDE T0 ON T.\"GUIDE_ID\"=T0.\"OBJECT_ID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Visa loadCurrentDeep(Cursor cursor, boolean lock) {
        Visa entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Guide guide = loadCurrentOther(daoSession.getGuideDao(), cursor, offset);
        entity.setGuide(guide);

        return entity;    
    }

    public Visa loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Visa> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Visa> list = new ArrayList<Visa>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Visa> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Visa> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
